Fix #196 melhorias local
wendybot/Wendy-Local pull request #11
Opened 2019-05-17 23:08 UTC by micaellagouveia

Nesse pull request foi feito:

Issue #196
Melhorias no microsserviço Gaia-Local.

2019-05-18 02:47 UTC, CalebeRios requested changes

2019-05-18 02:47 UTC, CalebeRios commented on src/test/indexText.js
> +
Linha desnecessária

2019-05-18 12:14 UTC, AmandaMuniz requested changes
Um pr foi aceito antes do seu. Por favor, atualize com a dev.

2019-05-21 02:03 UTC, CalebeRios approved these changes

2019-05-21 02:20 UTC, AmandaMuniz approved these changes

2019-05-21 02:20 UTC, merged