Fix #127 US12 Eu como usuário desejo que o sistema retorne o local com mais acurácia e precisão
wendybot/Wendy-Local pull request #5
Opened 2019-04-25 02:48 UTC by SamButers

Nesse pull request foi feito:

Mudanças no tratamento e formatação da resposta do Gaia Local
Remoção da model Local na lógica da requisição

2019-04-25 17:56 UTC, CalebeRios requested changes

2019-04-25 17:56 UTC, CalebeRios commented on src/requests/requestCoords.js
> +    for (c = 0; c < totalResults; c += 1) {
O que é c? Não é uma variavel nada significativa.

2019-04-25 23:01 UTC, AmandaMuniz approved these changes
O pr está respeitando a arquitetura. Só faz a mudança do nome da variável.

2019-04-25 23:01 UTC, AmandaMuniz commented on src/requests/requestCoords.js
> +    for (c = 0; c < totalResults; c += 1) {
RT

2019-04-26 00:11 UTC, CalebeRios approved these changes

2019-04-26 00:13 UTC, merged