Fix #128 US13 - Eu como usuário desejo que o serviço me indique os endpoints
wendybot/Wendy-Local pull request #8
Opened 2019-05-08 03:23 UTC by SamButers

Nesse pull request foi feito:

Adição das endpoints na raíz do Local.

2019-05-11 20:11 UTC, CalebeRios requested changes
Adicionar a rota principal no README

2019-05-11 20:11 UTC, CalebeRios commented on src/utils/endpoints.js
> +        description: 'Recebe o nome de um local e retorna as coordenadas do local informado',
Todo o json está em inglês, então fazer a alteração do `description` para inglês também.

2019-05-13 01:13 UTC, AmandaMuniz approved these changes

2019-05-13 23:36 UTC, CalebeRios approved these changes

2019-05-13 23:36 UTC, merged