Fix #188 US21 - Eu como usuário desejo que o sistema trate das opções de local repetidas
wendybot/Wendy-Local pull request #9
Opened 2019-05-16 04:10 UTC by SamButers

Nesse pull request foi feito:

Issue #188
User Story #21
Tratamento de opções de locais repetidas/próximas

2019-05-16 18:36 UTC, AmandaMuniz requested changes
Olá, você criou vários utils, eles estão sendo testados?

2019-05-16 18:36 UTC, AmandaMuniz commented on src/utils/localTreatment.js
> +function treatResults(resultsArray, selector, input) {
Essa função está muito grande. Tenta diminuir, por favor

2019-05-16 18:36 UTC, AmandaMuniz commented on src/utils/math.js
> +};
math.js não é um nome bom para um utils. Math em relação ao que? Um desenvolvedor externo tem que conseguir saber pelo menos o que cada file pode ter, a partir do seu nome

2019-05-16 18:36 UTC, AmandaMuniz commented on src/utils/math.js
> +    const a = Math.sin((lat[1] - lat[0]) / 2) * Math.sin((lat[1] - lat[0]) / 2) + Math.cos(lat[0])
a não é um nome significativo para constante

2019-05-16 18:36 UTC, AmandaMuniz commented on src/utils/math.js
> +    const b = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
b não é um nome significativo para constante

2019-05-16 18:36 UTC, AmandaMuniz commented on src/utils/localTreatment.js
> +          results.forEach((value2, index2) => {
Esse tratamento tem que ficar dentro de bodyToResultArray? Ou você pode passar para uma função e só chamá-la aqui dentro?

2019-05-16 21:53 UTC, SamButers commented on src/utils/math.js
> +};
Acredito que math.js seja um nome significativo.
math.js contém, como o nome implica, funções matemáticas e essas funções possuem nomes bem significativos, não creio que há qualquer problema em interpretar o intuito do arquivo e suas funções, afinal o objeto Math é semelhante a isso, nome simples e direto, e contém variadas funções matemáticas, como esperado.
Diante disso, crê que essa mudança seja realmente necessária?

2019-05-16 21:58 UTC, SamButers commented on src/utils/math.js
> +    const a = Math.sin((lat[1] - lat[0]) / 2) * Math.sin((lat[1] - lat[0]) / 2) + Math.cos(lat[0])
Tanto const a e const b são somente passos intermediários da Fórmula de Haversine, somente para melhor separação e organização.
Não teria problema em removê-las e colocar toda a fórmula no return, como também poderia mudar para haversine_a e haversine_b, se preferir.
Possui alguma preferência?

2019-05-16 22:17 UTC, SamButers commented on src/utils/localTreatment.js
> +function treatResults(resultsArray, selector, input) {
Se refere a treatResults?
Ela possuía muito mais linhas, mas foi quebrada, como também simplificada.
Atualmente, só possui declaração de variáveis, duas condicionais e dois loops um dentro do outro.
Acredito que esteja bem simples atualmente, mas creio que é possível mandar um ou dois desses loops para dentro de uma nova função, embora a criação de diversas funções não me alegra em relação ao aumento do número de passagens de parâmetros.
A ideia proposta satisfaria?

2019-05-16 22:25 UTC, SamButers commented on src/utils/localTreatment.js
> +          results.forEach((value2, index2) => {
O código dentro do forEach pode ser passado para uma função, sim.
Como deseja, irei fazê-lo.

2019-05-16 22:27 UTC, SamButers commented
> Olá, você criou vários utils, eles estão sendo testados?

De acordo com o relatório dos testes, as utils estão como 100% de cobertura nos testes e com cobertura maior de 94% em relação as linhas testadas, todavia elas não estão sendo testadas diretamente, mas sim indiretamente através do teste da rota listLocales.

2019-05-16 23:01 UTC, AmandaMuniz commented on src/utils/localTreatment.js
> +function treatResults(resultsArray, selector, input) {
Sim, agradaria. Atualmente treatResults vai da linha 19 até a 53, mesmo que seja simples é um número muito grande de linhas.

2019-05-16 23:07 UTC, AmandaMuniz commented on src/utils/math.js
> +};
No nosso caso, o file deve indicar onde essas funções estão trabalhando. Assim como o file de tratamento está indicando o local onde o faz "localTreatment", math.js deve fazer algo similar. É só uma questão de padronização da arquitetura. Por isso a mudança se torna necessária.

2019-05-16 23:08 UTC, AmandaMuniz commented on src/utils/math.js
> +    const a = Math.sin((lat[1] - lat[0]) / 2) * Math.sin((lat[1] - lat[0]) / 2) + Math.cos(lat[0])
Não é preciso colocar a fórmula no return, só passando para haversine_a e haversine_b é suficiente.

2019-05-16 23:21 UTC, SamButers commented on src/utils/math.js
> +};
Compreendo.
Criei a math.js com o pensamento de que ela não é isolada somente ao que estou fazendo agora, já que outro contexto pode aparecer para essas funções, como outras funções matemáticas podem surgir em outro momentos da aplicação e serem incluídas a essa utils.

2019-05-16 23:25 UTC, AmandaMuniz commented on src/utils/math.js
> +};
Caso isso ocorra, eu farei essa avaliação sobre o nome. Mas para respeitar a arquitetura atual deve ser mudado.

2019-05-17 00:49 UTC, AmandaMuniz requested changes
Olá, o nome do file localTreatmentMath não é bom. Peço desculpas porque acho que te confundi na hora que estava explicando. Quando falei de localTreatment.js era só um exemplo. Um nome que se adeque a arquitetura seria localMath ou coordMath, já que trabalha nisso

2019-05-17 01:07 UTC, AmandaMuniz approved these changes

2019-05-17 01:11 UTC, CalebeRios approved these changes

2019-05-17 01:12 UTC, merged